name: Run PHP and Save Results

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'

      - name: Run PHP Script and Save Results
        run: |
          php -S localhost:8000 > results/output.txt
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add results/output.txt
          git commit -m "Save PHP script results"
          git push origin main
